// export const FETCH_PETS = "FETCH_PETS"
// export const ADD_PET = "ADD_PET"
export const SET_CURRENT_PET = "SET_CURRENT_PET" //mdp PetCard msp app
export const BUY_ITEM = 'BUY_ITEM' //mdp ItemCard msp app
export const GET_BOUGHT = 'GET_BOUGHT' //mdp app msp app
export const GET_USER = 'GET_USER' //mdp app msp app
export const GET_PETS = 'GET_PETS' //mdp app msp app
export const ADD_PET = 'ADD_PET' ///mdp adopt msp app
export const GET_ITEMS = 'GET_ITEMS' //mdp app msp app
export const USE_ITEM = 'USE_ITEM' //mdp PetCard msp app
export const FEED_PET = 'FEED_PET' //mdp PetCard msp app
export const PLAY_WITH_PET = 'PLAY_WITH_PET' //mdp PetCard msp app 