// export const FETCH_PETS = "FETCH_PETS"
// export const ADD_PET = "ADD_PET"
export const SET_CURRENT_PET = "SET_CURRENT_PET" //mdp PetCard msp app
export const BUY_ITEM = 'BUY_ITEM' //mdp ItemCard msp app
export const GET_BOUGHT = 'GET_BOUGHT' //mdp app msp app
export const GET_USER = 'GET_USER' //mdp app msp app
export const GET_PETS = 'GET_PETS' //mdp app msp app
export const ADD_PET = 'ADD_PET' ///mdp adopt msp app
export const GET_ITEMS = 'GET_ITEMS' //mdp app msp app
export const USE_ITEM = 'USE_ITEM' //mdp PetCard msp app
export const FEED_PET = 'FEED_PET' //mdp PetCard msp app
export const PLAY_WITH_PET = 'PLAY_WITH_PET' //mdp PetCard msp app
export const DECREMENT_PET_HAPPINESS = 'DECREMENT_PET_HAPPINESS'
export const DECREMENT_PET_HUNGER = 'DECREMENT_PET_HUNGER'
export const GET_PET_HAPPINESS = 'GET_PET_HAPPINESS'
export const GET_PET_HUNGER = 'GET_PET_HUNGER'
export const INCREMENT_HAPPINESS = 'INCREMENT_HAPPINESS'
export const INCREMENT_HUNGER = 'INCREMENT_HUNGER'
export const DECREMENT_HAPPINESS = 'DECREMENT_HAPPINESS'
export const DECREMENT_HUNGER = 'DECREMENT_HUNGER'
export const UNSET_CURRENT_PET = 'UNSET_CURRENT_PET'
export const UN_BUY = 'UN_BUY'
export const AWARD_POINTS = 'AWARD_POINTS'
export const SPEND_POINTS = 'SPEND_POINTS'
export const SET_VAL = 'SET_VAL'
export const SET_HIGH_SCORE = 'SET_HIGH_SCORE'
export const GET_POINTS = 'GET_POINTS'
// export const GET_BOUGHT_BOOL = 'GET_BOUGHT_BOOL'
// export const SET_BOUGHT_BOOL = 'SET_BOUGHT_BOOL'

