// export const FETCH_PETS = "FETCH_PETS"
// export const ADD_PET = "ADD_PET"
export const SET_CURRENT_PET = "SET_CURRENT_PET"
export const BUY_ITEM = 'BUY_ITEM'
export const GET_BOUGHT = 'GET_BOUGHT'
export const GET_USER = 'GET_USER'
export const GET_PETS = 'GET_PETS'
export const ADD_PET = 'ADD_PET'
export const GET_ITEMS = 'GET_ITEMS'